[build]
  base = "brandfront"
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  REACT_APP_API_URL = "https://BrandFlow-production-7e3b.up.railway.app/api"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200